In [72]:
import pandas as pd
import numpy as np

In [73]:
df=pd.read_csv("crop_production.csv")

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 246091 entries, 0 to 246090
Data columns (total 7 columns):
State_Name       246091 non-null object
District_Name    246091 non-null object
Crop_Year        246091 non-null int64
Season           246091 non-null object
Crop             246091 non-null object
Area             246091 non-null float64
Production       242361 non-null float64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.1+ MB

In [75]:
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()
label.fit(df['State_Name'])
df['State_Name']=label.transform(df['State_Name'])

In [76]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 246091 entries, 0 to 246090
Data columns (total 7 columns):
State_Name       246091 non-null int32
District_Name    246091 non-null object
Crop_Year        246091 non-null int64
Season           246091 non-null object
Crop             246091 non-null object
Area             246091 non-null float64
Production       242361 non-null float64
dtypes: float64(2), int32(1), int64(1), object(3)
memory usage: 12.2+ MB

In [77]:
df

,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production
0,0,NICOBARS,2000,Kharif,Arecanut,1254.0,2000.00
1,0,NICOBARS,2000,Kharif,Other Kharif pulses,2.0,1.00
2,0,NICOBARS,2000,Kharif,Rice,102.0,321.00
3,0,NICOBARS,2000,Whole Year,Banana,176.0,641.00
4,0,NICOBARS,2000,Whole Year,Cashewnut,720.0,165.00
5,0,NICOBARS,2000,Whole Year,Coconut,18168.0,65100000.00
6,0,NICOBARS,2000,Whole Year,Dry ginger,36.0,100.00
7,0,NICOBARS,2000,Whole Year,Sugarcane,1.0,2.00
8,0,NICOBARS,2000,Whole Year,Sweet potato,5.0,15.00
9,0,NICOBARS,2000,Whole Year,Tapioca,40.0,169.00
10,0,NICOBARS,2001,Kharif,Arecanut,1254.0,2061.00
11,0,NICOBARS,2001,Kharif,Other Kharif pulses,2.0,1.00
12,0,NICOBARS,2001,Kharif,Rice,83.0,300.00
13,0,NICOBARS,2001,Whole Year,Cashewnut,719.0,192.00
14,0,NICOBARS,2001,Whole Year,Coconut,18190.0,64430000.00
15,0,NICOBARS,2001,Whole Year,Dry ginger,46.0,100.00
16,0,NICOBARS,2001,Whole Year,Sugarcane,1.0,1.00
17,0,NICOBARS,2001,Whole Year,Sweet potato,11.0,33.00
18,0,NICOBARS,2002,Kharif,Rice,189.2,510.84
19,0,NICOBARS,2002,Whole Year,Arecanut,1258.0,2083.00
20,0,NICOBARS,2002,Whole Year,Banana,213.0,1278.00
21,0,NICOBARS,2002,Whole Year,Black pepper,63.0,13.50
22,0,NICOBARS,2002,Whole Year,Cashewnut,719.0,208.00
23,0,NICOBARS,2002,Whole Year,Coconut,18240.0,67490000.00
24,0,NICOBARS,2002,Whole Year,Dry chillies,413.0,28.80
25,0,NICOBARS,2002,Whole Year,Dry ginger,47.3,133.00
26,0,NICOBARS,2002,Whole Year,Sugarcane,5.0,40.00
27,0,NICOBARS,2003,Kharif,Rice,52.0,90.17
28,0,NICOBARS,2003,Whole Year,Arecanut,1261.0,1525.00
29,0,NICOBARS,2003,Whole Year,Banana,266.0,1763.00
...,...,...,...,...,...,...,...
246061,32,PURULIA,2014,Kharif,Bajra,49.0,19.00
246062,32,PURULIA,2014,Kharif,Mesta,159.0,2065.00
246063,32,PURULIA,2014,Kharif,Moong(Green Gram),181.0,100.00
246064,32,PURULIA,2014,Kharif,Moth,16.0,14.00
246065,32,PURULIA,2014,Kharif,Niger seed,204.0,74.00
246066,32,PURULIA,2014,Kharif,Other Kharif pulses,79.0,39.00
246067,32,PURULIA,2014,Kharif,Sannhamp,171.0,727.00
246068,32,PURULIA,2014,Kharif,Soyabean,18.0,7.00
246069,32,PURULIA,2014,Kharif,Sunflower,46.0,42.00
246070,32,PURULIA,2014,Kharif,Urad,11493.0,3287.00
246071,32,PURULIA,2014,Rabi,Arhar/Tur,671.0,723.00
246072,32,PURULIA,2014,Rabi,Gram,198.0,203.00
246073,32,PURULIA,2014,Rabi,Groundnut,30.0,25.00
246074,32,PURULIA,2014,Rabi,Horse-gram,660.0,332.00
246075,32,PURULIA,2014,Rabi,Khesari,146.0,126.00
246076,32,PURULIA,2014,Rabi,Linseed,160.0,51.00
246077,32,PURULIA,2014,Rabi,Masoor,31.0,19.00
246078,32,PURULIA,2014,Rabi,Moong(Green Gram),64.0,40.00
246079,32,PURULIA,2014,Rabi,Peas & beans (Pulses),12.0,12.00
246080,32,PURULIA,2014,Rabi,Potato,477.0,9995.00
246081,32,PURULIA,2014,Rabi,Rapeseed &Mustard,1885.0,1508.00
246082,32,PURULIA,2014,Rabi,Safflower,54.0,37.00
246083,32,PURULIA,2014,Rabi,Urad,220.0,113.00
246084,32,PURULIA,2014,Rabi,Wheat,1622.0,3663.00
246085,32,PURULIA,2014,Summer,Maize,325.0,2039.00
246086,32,PURULIA,2014,Summer,Rice,306.0,801.00
246087,32,PURULIA,2014,Summer,Sesamum,627.0,463.00
246088,32,PURULIA,2014,Whole Year,Sugarcane,324.0,16250.00
246089,32,PURULIA,2014,Winter,Rice,279151.0,597899.00
246090,32,PURULIA,2014,Winter,Sesamum,175.0,88.00

In [78]:
label.fit(df['District_Name'])
df['District_Name']=label.transform(df['District_Name'])

In [79]:
label.fit(df['Season'])
df['Season']=label.transform(df['Season'])

In [80]:
label.fit(df['Crop'])
df['Crop']=label.transform(df['Crop'])

In [81]:
df=df.drop(["Crop_Year"],axis=1)
df

        State_Name  District_Name  Season  Crop      Area   Production
0                0            427       1     2    1254.0      2000.00
1                0            427       1    74       2.0         1.00
2                0            427       1    95     102.0       321.00
3                0            427       4     7     176.0       641.00
4                0            427       4    22     720.0       165.00
5                0            427       4    28   18168.0  65100000.00
6                0            427       4    38      36.0       100.00
7                0            427       4   106       1.0         2.00
8                0            427       4   108       5.0        15.00
9                0            427       4   109      40.0       169.00
10               0            427       1     2    1254.0      2061.00
11               0            427       1    74       2.0         1.00
12               0            427       1    95      83.0       300.00
13               0            427       4    22     719.0       192.00
14               0            427       4    28   18190.0  64430000.00
15               0            427       4    38      46.0       100.00
16               0            427       4   106       1.0         1.00
17               0            427       4   108      11.0        33.00
18               0            427       1    95     189.2       510.84
19               0            427       4     2    1258.0      2083.00
20               0            427       4     7     213.0      1278.00
21               0            427       4    15      63.0        13.50
22               0            427       4    22     719.0       208.00
23               0            427       4    28   18240.0  67490000.00
24               0            427       4    37     413.0        28.80
25               0            427       4    38      47.3       133.00
26               0            427       4   106       5.0        40.00
27               0            427       1    95      52.0        90.17
28               0            427       4     2    1261.0      1525.00
29               0            427       4     7     266.0      1763.00
...            ...            ...     ...   ...       ...          ...
246061          32            471       1     6      49.0        19.00
246062          32            471       1    62     159.0      2065.00
246063          32            471       1    63     181.0       100.00
246064          32            471       1    64      16.0        14.00
246065          32            471       1    65     204.0        74.00
246066          32            471       1    74      79.0        39.00
246067          32            471       1   100     171.0       727.00
246068          32            471       1   105      18.0         7.00
246069          32            471       1   107      46.0        42.00
246070          32            471       1   116   11493.0      3287.00
246071          32            471       2     3     671.0       723.00
246072          32            471       2    41     198.0       203.00
246073          32            471       2    43      30.0        25.00
246074          32            471       2    45     660.0       332.00
246075          32            471       2    52     146.0       126.00
246076          32            471       2    57     160.0        51.00
246077          32            471       2    61      31.0        19.00
246078          32            471       2    63      64.0        40.00
246079          32            471       2    81      12.0        12.00
246080          32            471       2    87     477.0      9995.00
246081          32            471       2    92    1885.0      1508.00
246082          32            471       2    98      54.0        37.00
246083          32            471       2   116     220.0       113.00
246084          32            471       2   119    1622.0      3663.00
246085          32            471       3    59     325.0      2039.00
246086          32            471       3    95     306.0       801.00
246087          32            471       3   102     627.0       463.00
246088          32            471       4   106     324.0     16250.00
246089          32            471       5    95  279151.0    597899.00
246090          32            471       5   102     175.0        88.00

[246091 rows x 6 columns]

In [82]:
df.isna().sum()

State_Name          0
District_Name       0
Season              0
Crop                0
Area                0
Production       3730
dtype: int64

In [83]:
prod=df["Production"]

In [84]:
prod.fillna(prod.mode()[0],inplace=True)

In [85]:
df.isna().sum()

State_Name       0
District_Name    0
Season           0
Crop             0
Area             0
Production       0
dtype: int64

In [86]:
from sklearn.linear_model import LinearRegression
y = df["Production"].values
X = df.drop(["Production"],axis=1).values
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [87]:
reg_all=LinearRegression()
reg_all.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [95]:
pre=[0,427,1,2,1254]
pre = np.squeeze(np.asarray(pre))
pre=pre.reshape(1,-1)
pre.shape

(1, 5)

In [96]:
reg_all.predict(pre)

array([1439759.65826847])